### PR TITLE
feat: :sparkles: add custom http method request

### PR DESCRIPTION
**Pull request by bungambohlah**
add an feature of custom http method request (by default use `GET`).
this will solve issue at #25.

And this already run gulp task for create dist files for prod ready.

And please add `hacktoberfest` label. Thank you

### CODE REVIEW

**Comment by Trekky12** [comment]
Thank you for your contribution. Could you please send your PR to the development branch instead the master branch?

**Comment by bungambohlah** [comment]
Hi @Trekky12, any updates?

**Comment by Trekky12** [comment]
Thank you for your adjustments.
I will merge your PR in a few days. I assigned the hacktoberfest-accepted label so it should count for your challenge.

**Comment by bungambohlah** [comment]
@Trekky12 You're welcome, ok noted that, thank you so much for your help to open this hacktoberfest as maintainer

**Pull request merged**
